# Generated by Django 4.2.1 on 2023-10-30 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('pal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pal')),
            ],
        ),
    ]
